//! Advanced SIP registration scenarios run against a real Asterisk PBX.
//!
//! These tests are gated on Asterisk being installed locally (the framework
//! spawns it as a subprocess). They exercise interop quirks that the
//! local-pair tests in `registration.rs` cannot — real digest auth from
//! pjsip_resource_authentication, contact AOR storage, expiry semantics,
//! multiple-contact handling, etc.
//!
//! When Asterisk is not installed the tests skip cleanly with a message.

use std::net::SocketAddr;
use std::time::Duration;

use rsiprtp::sip::{DigestChallenge, DigestCredentials, DigestResponse};

use crate::framework::{AsteriskConfig, AsteriskInstance, TestConfig, TestEndpoint};

/// Default test user from the Asterisk pjsip.conf generated by the framework.
const TEST_USER: &str = "1001";
const TEST_PASS: &str = "test1001";

/// Helper to check if Asterisk is available
fn is_asterisk_available() -> bool {
    AsteriskInstance::is_available()
}

/// Spin up an Asterisk instance for a test, returning it along with a
/// freshly-bound TestEndpoint and the registrar address. Returns `None`
/// (with eprintln) if Asterisk isn't installed or AMI never comes up — the
/// caller should `?` / early-return on `None`.
async fn spawn_asterisk_and_endpoint(
    label: &str,
) -> Option<(AsteriskInstance, TestEndpoint, SocketAddr)> {
    if !is_asterisk_available() {
        eprintln!("Skipping {label}: asterisk not installed");
        return None;
    }

    let test_config = TestConfig::with_available_ports();
    let ast_config = AsteriskConfig::new_test(
        std::env::temp_dir().join(format!("ast_{label}")),
        test_config.local_sip_port + 100,
        test_config.local_sip_port + 101,
    );

    let mut asterisk = AsteriskInstance::new(ast_config.clone()).ok()?;
    tokio::time::sleep(Duration::from_secs(2)).await;
    if asterisk.connect_ami().await.is_err() {
        eprintln!("Skipping {label}: Asterisk AMI did not come up");
        return None;
    }

    let endpoint = TestEndpoint::new(test_config.clone()).await.ok()?;
    let registrar_addr: SocketAddr = format!("127.0.0.1:{}", asterisk.sip_port())
        .parse()
        .unwrap();

    Some((asterisk, endpoint, registrar_addr))
}

/// Find a header value (case-insensitive) in a SIP message.
fn find_header(msg: &str, name: &str) -> Option<String> {
    let needle = format!("{}:", name.to_lowercase());
    for line in msg.lines() {
        if line.to_lowercase().starts_with(&needle) {
            return Some(line[needle.len()..].trim().to_string());
        }
    }
    None
}

/// Build a REGISTER request. `contact_extra` is appended to the Contact
/// header URI angle brackets, e.g. `;expires=120;q=0.5`.
#[allow(clippy::too_many_arguments)]
fn build_register(
    from_uri: &str,
    to_uri: &str,
    contact_uri: &str,
    contact_extra: &str,
    call_id: &str,
    cseq: u32,
    expires: u32,
    via_port: u16,
    branch: &str,
    from_tag: &str,
    authorization: Option<&str>,
) -> String {
    let auth_line = match authorization {
        Some(a) => format!("Authorization: {a}\r\n"),
        None => String::new(),
    };

    format!(
        "REGISTER {to_uri} SIP/2.0\r\n\
         Via: SIP/2.0/UDP 127.0.0.1:{via_port};branch={branch};rport\r\n\
         Max-Forwards: 70\r\n\
         From: <{from_uri}>;tag={from_tag}\r\n\
         To: <{to_uri}>\r\n\
         Call-ID: {call_id}\r\n\
         CSeq: {cseq} REGISTER\r\n\
         Contact: <{contact_uri}>{contact_extra}\r\n\
         Expires: {expires}\r\n\
         {auth_line}\
         Content-Length: 0\r\n\
         \r\n",
    )
}

/// Drive a complete REGISTER + 401 + authenticated REGISTER round trip
/// against Asterisk and return the final 200 OK response body.
///
/// Returns the response string on success, or an error message describing
/// what went wrong. Asserts internally that the final response is 200 OK.
#[allow(clippy::too_many_arguments)]
async fn authenticated_register(
    endpoint: &TestEndpoint,
    registrar_addr: SocketAddr,
    user: &str,
    password: &str,
    contact_extra: &str,
    expires: u32,
    call_id: &str,
    contact_uri: &str,
) -> Result<String, String> {
    let local_port = endpoint.local_sip_port();
    let to_uri = format!("sip:{user}@127.0.0.1:{}", registrar_addr.port());
    let from_uri = to_uri.clone();
    let from_tag = format!("tag-{}", uuid::Uuid::new_v4().simple());

    // Round 1: unauthenticated REGISTER
    let req1 = build_register(
        &from_uri,
        &to_uri,
        contact_uri,
        contact_extra,
        call_id,
        1,
        expires,
        local_port,
        &format!("z9hG4bK-{}", uuid::Uuid::new_v4().simple()),
        &from_tag,
        None,
    );
    endpoint
        .send_raw(&req1, registrar_addr)
        .await
        .map_err(|e| format!("send round 1: {e}"))?;
    let (resp1, _) = endpoint
        .recv_raw(Duration::from_secs(3))
        .await
        .map_err(|e| format!("recv round 1: {e}"))?;
    let resp1_str = String::from_utf8_lossy(&resp1).to_string();
    if !resp1_str.starts_with("SIP/2.0 401") && !resp1_str.starts_with("SIP/2.0 407") {
        return Err(format!(
            "expected 401/407 challenge, got: {}",
            resp1_str.lines().next().unwrap_or("")
        ));
    }

    let challenge_value = find_header(&resp1_str, "WWW-Authenticate")
        .or_else(|| find_header(&resp1_str, "Proxy-Authenticate"))
        .ok_or_else(|| "401/407 missing challenge header".to_string())?;
    let challenge = DigestChallenge::parse(&challenge_value)
        .map_err(|e| format!("parse challenge: {e}"))?;
    let creds = DigestCredentials::new(user, password);
    let response =
        DigestResponse::from_challenge(&challenge, &creds, "REGISTER", &to_uri, None)
            .map_err(|e| format!("compute digest: {e}"))?;

    // Round 2: authenticated REGISTER
    let req2 = build_register(
        &from_uri,
        &to_uri,
        contact_uri,
        contact_extra,
        call_id,
        2,
        expires,
        local_port,
        &format!("z9hG4bK-{}", uuid::Uuid::new_v4().simple()),
        &from_tag,
        Some(&response.to_header_value()),
    );
    endpoint
        .send_raw(&req2, registrar_addr)
        .await
        .map_err(|e| format!("send round 2: {e}"))?;

    // Asterisk may emit one or more provisional/info responses; accept the
    // first 2xx that matches our Call-ID.
    let deadline = tokio::time::Instant::now() + Duration::from_secs(3);
    loop {
        let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
        if remaining.is_zero() {
            return Err("timed out waiting for 200 OK".to_string());
        }
        let (resp, _) = endpoint
            .recv_raw(remaining)
            .await
            .map_err(|e| format!("recv round 2: {e}"))?;
        let resp_str = String::from_utf8_lossy(&resp).to_string();
        if find_header(&resp_str, "Call-ID").as_deref() != Some(call_id) {
            continue;
        }
        if resp_str.starts_with("SIP/2.0 200") {
            return Ok(resp_str);
        }
        if resp_str.starts_with("SIP/2.0 1") {
            // Provisional — keep waiting.
            continue;
        }
        return Err(format!(
            "expected 200 OK, got: {}",
            resp_str.lines().next().unwrap_or("")
        ));
    }
}

/// Test the full REGISTER + 401 + authenticated REGISTER + 200 OK flow
/// against a real Asterisk registrar.
#[tokio::test]
#[ignore = "requires asterisk to be installed"]
async fn test_register_with_asterisk() {
    let Some((_asterisk, endpoint, registrar_addr)) =
        spawn_asterisk_and_endpoint("register_with_asterisk").await
    else {
        return;
    };

    let call_id = uuid::Uuid::new_v4().to_string();
    let contact_uri = format!("sip:{TEST_USER}@127.0.0.1:{}", endpoint.local_sip_port());
    let resp = authenticated_register(
        &endpoint,
        registrar_addr,
        TEST_USER,
        TEST_PASS,
        "",
        3600,
        &call_id,
        &contact_uri,
    )
    .await
    .expect("authenticated REGISTER must succeed against Asterisk");

    assert!(resp.starts_with("SIP/2.0 200"));
    // Asterisk echoes Contact with an expires= parameter on the registered binding.
    let contact = find_header(&resp, "Contact").expect("200 OK must carry Contact");
    assert!(
        contact.contains("expires=") || find_header(&resp, "Expires").is_some(),
        "200 OK must indicate a binding lifetime: contact={contact}"
    );
}

/// Test that a custom `Expires` value is respected (or capped) by Asterisk.
#[tokio::test]
#[ignore = "requires asterisk to be installed"]
async fn test_register_with_expiry() {
    let Some((_asterisk, endpoint, registrar_addr)) =
        spawn_asterisk_and_endpoint("register_with_expiry").await
    else {
        return;
    };

    let requested_expiry = 120u32;
    let call_id = uuid::Uuid::new_v4().to_string();
    let contact_uri = format!("sip:{TEST_USER}@127.0.0.1:{}", endpoint.local_sip_port());
    let resp = authenticated_register(
        &endpoint,
        registrar_addr,
        TEST_USER,
        TEST_PASS,
        "",
        requested_expiry,
        &call_id,
        &contact_uri,
    )
    .await
    .expect("authenticated REGISTER with custom expiry must succeed");

    // Asterisk may cap or use the asked-for value. Accept anything that's
    // > 0 and <= the requested value (cap), or equal to it. The key
    // property is that it does NOT silently drop to its default 3600.
    let granted = find_header(&resp, "Expires")
        .and_then(|s| s.parse::<u32>().ok())
        .or_else(|| {
            // Some servers return only Contact;expires=N
            find_header(&resp, "Contact")
                .and_then(|c| {
                    c.split(';')
                        .find_map(|p| p.trim().strip_prefix("expires="))
                        .and_then(|v| v.parse::<u32>().ok())
                })
        })
        .expect("200 OK must report granted lifetime");

    assert!(
        granted > 0 && granted <= requested_expiry,
        "granted expiry {granted} should be within (0, {requested_expiry}]"
    );
}

/// Test refreshing an existing registration.
#[tokio::test]
#[ignore = "requires asterisk to be installed"]
async fn test_registration_refresh() {
    let Some((_asterisk, endpoint, registrar_addr)) =
        spawn_asterisk_and_endpoint("registration_refresh").await
    else {
        return;
    };

    let call_id = uuid::Uuid::new_v4().to_string();
    let contact_uri = format!("sip:{TEST_USER}@127.0.0.1:{}", endpoint.local_sip_port());

    // First registration
    let resp1 = authenticated_register(
        &endpoint,
        registrar_addr,
        TEST_USER,
        TEST_PASS,
        "",
        300,
        &call_id,
        &contact_uri,
    )
    .await
    .expect("initial REGISTER must succeed");
    assert!(resp1.starts_with("SIP/2.0 200"));

    // Brief pause then refresh — Asterisk should accept a fresh
    // REGISTER for the same AOR/Call-ID and issue another 200.
    tokio::time::sleep(Duration::from_millis(200)).await;
    let resp2 = authenticated_register(
        &endpoint,
        registrar_addr,
        TEST_USER,
        TEST_PASS,
        "",
        300,
        // New Call-ID for the refresh — pjsip allows but doesn't require
        // reuse, and we want to verify either way works.
        &uuid::Uuid::new_v4().to_string(),
        &contact_uri,
    )
    .await
    .expect("refresh REGISTER must succeed");
    assert!(resp2.starts_with("SIP/2.0 200"));
}

/// Test unregister via `Expires: 0`.
#[tokio::test]
#[ignore = "requires asterisk to be installed"]
async fn test_unregister_expires_zero() {
    let Some((_asterisk, endpoint, registrar_addr)) =
        spawn_asterisk_and_endpoint("unregister_expires_zero").await
    else {
        return;
    };

    let call_id_reg = uuid::Uuid::new_v4().to_string();
    let contact_uri = format!("sip:{TEST_USER}@127.0.0.1:{}", endpoint.local_sip_port());

    // Register first
    let resp1 = authenticated_register(
        &endpoint,
        registrar_addr,
        TEST_USER,
        TEST_PASS,
        "",
        3600,
        &call_id_reg,
        &contact_uri,
    )
    .await
    .expect("initial REGISTER must succeed");
    assert!(resp1.starts_with("SIP/2.0 200"));

    // Unregister with Expires: 0
    let call_id_unreg = uuid::Uuid::new_v4().to_string();
    let resp2 = authenticated_register(
        &endpoint,
        registrar_addr,
        TEST_USER,
        TEST_PASS,
        "",
        0,
        &call_id_unreg,
        &contact_uri,
    )
    .await
    .expect("unregister REGISTER must succeed");
    assert!(resp2.starts_with("SIP/2.0 200"));

    // The 200 OK to unregister should not advertise an active binding
    // (either no Contact, or Contact with expires=0).
    let contact = find_header(&resp2, "Contact").unwrap_or_default();
    let expires = find_header(&resp2, "Expires").unwrap_or_default();
    let removed = contact.is_empty()
        || contact.contains("expires=0")
        || expires.trim() == "0";
    assert!(
        removed,
        "200 OK to unregister should signal removal: contact={contact:?} expires={expires:?}"
    );
}

/// Test registration of two distinct contacts under the same AOR.
#[tokio::test]
#[ignore = "requires asterisk to be installed"]
async fn test_register_multiple_contacts() {
    let Some((_asterisk, endpoint_a, registrar_addr)) =
        spawn_asterisk_and_endpoint("multiple_contacts_a").await
    else {
        return;
    };

    // Second endpoint on a different SIP port — represents a different
    // device for the same user (e.g. desk phone + softphone).
    let test_config_b = TestConfig::with_available_ports();
    let endpoint_b = TestEndpoint::new(test_config_b.clone()).await.unwrap();

    let contact_a = format!("sip:{TEST_USER}@127.0.0.1:{}", endpoint_a.local_sip_port());
    let contact_b = format!("sip:{TEST_USER}@127.0.0.1:{}", endpoint_b.local_sip_port());

    let resp_a = authenticated_register(
        &endpoint_a,
        registrar_addr,
        TEST_USER,
        TEST_PASS,
        "",
        3600,
        &uuid::Uuid::new_v4().to_string(),
        &contact_a,
    )
    .await
    .expect("first endpoint REGISTER must succeed");
    assert!(resp_a.starts_with("SIP/2.0 200"));

    let resp_b = authenticated_register(
        &endpoint_b,
        registrar_addr,
        TEST_USER,
        TEST_PASS,
        "",
        3600,
        &uuid::Uuid::new_v4().to_string(),
        &contact_b,
    )
    .await
    .expect("second endpoint REGISTER must succeed");
    assert!(resp_b.starts_with("SIP/2.0 200"));

    // The 200 OK to the second register should list both contacts now bound
    // to the AOR (or at least the new one). max_contacts=5 in the
    // generated pjsip.conf so neither should be evicted.
    let contact_field = find_header(&resp_b, "Contact").unwrap_or_default();
    assert!(
        !contact_field.is_empty(),
        "200 OK must list at least the new Contact"
    );
}

/// Test that Asterisk accepts a Contact with per-contact `expires=` parameter.
#[tokio::test]
#[ignore = "requires asterisk to be installed"]
async fn test_register_contact_params() {
    let Some((_asterisk, endpoint, registrar_addr)) =
        spawn_asterisk_and_endpoint("contact_params").await
    else {
        return;
    };

    let per_contact_expiry = 90u32;
    let call_id = uuid::Uuid::new_v4().to_string();
    let contact_uri = format!("sip:{TEST_USER}@127.0.0.1:{}", endpoint.local_sip_port());
    // Per-Contact expires + q-value
    let contact_extra = format!(";expires={per_contact_expiry};q=0.7");

    // Use a header-level Expires that contradicts the per-Contact one to
    // verify Asterisk follows the per-Contact value (RFC 3261 §10.2.4: the
    // contact-level expires takes precedence).
    let resp = authenticated_register(
        &endpoint,
        registrar_addr,
        TEST_USER,
        TEST_PASS,
        &contact_extra,
        3600,
        &call_id,
        &contact_uri,
    )
    .await
    .expect("REGISTER with contact params must succeed");
    assert!(resp.starts_with("SIP/2.0 200"));

    let contact = find_header(&resp, "Contact").expect("200 OK must carry Contact");
    let granted = contact
        .split(';')
        .find_map(|p| p.trim().strip_prefix("expires="))
        .and_then(|v| v.parse::<u32>().ok())
        .expect("Contact in 200 OK must carry expires=");
    assert!(
        granted > 0 && granted <= per_contact_expiry,
        "per-Contact expiry should be honored: requested {per_contact_expiry}, got {granted}"
    );
}

#[cfg(test)]
mod unit_tests {
    use super::*;

    #[test]
    fn test_build_register_with_auth() {
        let req = build_register(
            "sip:1001@example.com",
            "sip:example.com",
            "sip:1001@192.168.1.1:5060",
            "",
            "abc-call-id",
            2,
            3600,
            5060,
            "z9hG4bK-xyz",
            "from-tag",
            Some("Digest username=\"1001\""),
        );

        assert!(req.contains("REGISTER sip:example.com SIP/2.0"));
        assert!(req.contains("CSeq: 2 REGISTER"));
        assert!(req.contains("Authorization: Digest username=\"1001\""));
        assert!(req.contains("Contact: <sip:1001@192.168.1.1:5060>"));
    }

    #[test]
    fn test_build_register_with_contact_params() {
        let req = build_register(
            "sip:1001@example.com",
            "sip:example.com",
            "sip:1001@192.168.1.1:5060",
            ";expires=120;q=0.5",
            "abc",
            1,
            3600,
            5060,
            "branch",
            "tag",
            None,
        );
        assert!(req.contains("Contact: <sip:1001@192.168.1.1:5060>;expires=120;q=0.5"));
    }

    #[test]
    fn test_find_header_works() {
        let msg = "SIP/2.0 200 OK\r\nContact: <sip:foo>;expires=60\r\n\r\n";
        assert_eq!(
            find_header(msg, "Contact").as_deref(),
            Some("<sip:foo>;expires=60")
        );
    }

    #[test]
    fn test_asterisk_available_check() {
        // Just verify this doesn't panic
        let _available = is_asterisk_available();
    }
}
