INVITE sip:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaABCDEFGHIJK_-+~*'1234567890@example.com SIP/2.0
To: "Watson, Thomas A. very long display name very long display name very long display name very long display name very long display name very long display name very long display name very long display name " <sip:t.watson@example.com>
From: "Watson, Thomas A. very long display name very long display name very long display name very long display name very long display name very long display name very long display name very long display name " <sip:a.bell@example.com>;tag=longtag-3434523ab98sdfn
Max-Forwards: 70
Call-ID: longreq.onetwothree@example.com
CSeq: 3882340 INVITE
Via: SIP/2.0/TCP sip-proxy.example.com;branch=z9hG4bKlongbranchhdgklstuvgaeoijflasdkfjhgwoeijdf32rj
Contact: <sip:caller@host5.example.com>
Content-Length: 0

