OPTIONS sip:user@example.com SIP/2.0
To: sip:user@example.com
From: sip:caller@example.org;tag=8392939323
Max-Forwards: 60
Call-ID: transports.kdjuw23-asdjf2349wjasdf
CSeq: 3 OPTIONS
Via: SIP/2.0/UDP t1.example.com;branch=z9hG4bK1aabccdd
Via: SIP/2.0/TCP t2.example.com;branch=z9hG4bK2
Via: SIP/2.0/SCTP t3.example.com;branch=z9hG4bK3
Via: SIP/2.0/TLS t4.example.com;branch=z9hG4bK4
Via: SIP/2.0/TLS-SCTP t5.example.com;branch=z9hG4bK5
Via: SIP/2.0/TUNA t6.example.com;branch=z9hG4bK6
L: 0

